{{/*
Copyright RisingWave Labs
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "risingwave.fullname" . }}
  labels:
    {{- include "risingwave.labels" . | nindent 4 }}
    apps.risingwave.com/component: frontend
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  {{- $annotations := (include "risingwave.annotations" . ) | trim }}
  {{- if $annotations }}
  annotations:
    {{ nindent 4 $annotations }}
  {{- end }}
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  externalIPs:
  {{- range .Values.service.externalIPs }}
  - {{ . }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ toYaml .Values.service.loadBalancerSourceRanges | indent 2 }}
  {{- end }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- toYaml .Values.service.sessionAffinityConfig | indent 4 }}
  {{- end }}
  selector:
    {{- include "risingwave.selectorLabels" . | nindent 4 }}
    {{- if .Values.compactMode.enabled }}
    apps.risingwave.com/component: compute
    {{- else }}
    apps.risingwave.com/component: frontend
    {{- end }}
  ports:
  - name: svc
    port: {{ .Values.service.port }}
    {{- if .Values.compactMode.enabled }}
    targetPort: f-svc
    {{- else }}
    targetPort: svc
    {{- end }}
    {{- if or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer") }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}